ppw4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('ppwstory4.urls')),
]

ppwstory4/urls.py
from django.urls import include, path
from . import views

app_name = 'ppwstory4'

urlpatterns = [
    path('', views.index, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('gallery/', views.gallery, name = 'gallery'),
]

ppwstory4/models.py
from django.db import models

# Create your models here.

ppwstory4/views.py
from django.shortcuts import render
from django.http import HttpResponse

# def index (request):
#     response = {'name' : 'Syauqi'}
#     return render (request, 'index.html', response)

def index (request):
    return render (request, 'mainbootstrap.html')

def about (request):
    return render (request, 'about.html')

def gallery (request):
    return render (request, 'gallery.html')


# Create your views here.

ppwstory4/templates/about.html
<!DOCTYPE html>
{% load static %}
<head>
	<meta charset = "UTF-8">
	<title>Tentang - Website Saya</title>
  <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Semi+Condensed&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel = "stylesheet"
   		type = "text/css"
   		href = "{% static 'css\cssStory3.css' %}" />
</head>
 
<body data-spy="scroll" data-target="#collapsibleNavbar">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <span class="navbar-brand" href="#">i am <b>uqi</b></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ppwstory4:home' %}">home</a></li>
          <li class="nav-item">
            <a class="active nav-link" href="#">ABOUT</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ppwstory4:gallery' %}">gallery</a></li>      
      </ul>
    </div>
  </nav>

    <p class="fullname">SYA<b>UQI</b> MUHAMMAD DHIYA ULHAQ</p>
    <p class="npm">1806235694</p>

    <div class="container">
      <div class="row">
        <div class="col-sm-4 col-lg-5">
          <img class = "fotoprofil" src="{% static 'images/Profil.jpg' %}" alt="Foto Profil" width="385">
        </div>
        <div class="col-sm-6 col-lg-5">
          <p class="kelas">informatics system student</p>
          <p class="institution">faculty of computer science universitas indonesia</p>
          <p class="kelas"> class of 2018</p>
          <p class="institution">3 senior high school of jakarta</p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4 col-lg-5"></div>
          <div class="col-sm-6 col-lg-5">
            <p class="exp">fun with:</p>
            <p class="nameofprog">python</p>
            <p class="nameofprog">java</p>
            <p class="nameofprog">HTML</p>
            <p class="nameofprog">CSS</p>
          </div>
      </div>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  </body>
</html>

ppwstory4/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<head>
	<meta charset = "UTF-8">
	<title>Galeri - Website Saya</title>
  <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Semi+Condensed&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel = "stylesheet"
   		type = "text/css"
   		href = "{% static 'css\cssStory3.css' %}" />
</head>
 
<body data-spy="scroll" data-target="#collapsibleNavbar">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <span class="navbar-brand" href="#">i am <b>uqi</b></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ppwstory4:home' %}">home</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ppwstory4:about' %}">about</a></li>
          <li class="nav-item">
            <a class="active nav-link" href="#">GALLERY</a></li>      
      </ul>
    </div>
  </nav>

  <p class="judul"><u>sebuah cerita yang ditampung dalam fotografi seorang awam</u></p>

  <div class="container">
    <div class="row gambar-container">
      <div class="col-sm-6 col-lg-5 gambar">
        <div class="panel d-flex align-content-center justify-content-center "><img src="{% static 'images/PelicanHI.jpg' %}" alt="Pelican Crossing HI" class="fotoingrid"></div>
      </div>
      <div class="col-sm-6 col-lg-5 gambar">
        <div class="panel d-flex align-content-center justify-content-center "><img src="{% static 'images/Rektorat.jpg' %}" alt="Rektorat" class="fotoingrid"></div>
      </div>
      <div class="col-sm-6 col-lg-5 gambar">
         <div class="panel d-flex align-content-center justify-content-center "><img src="{% static 'images/BusListrik.jpg' %}" alt="Pameran Bus Listrik" class="fotoingrid"></div>     
      </div>
      <div class="col-sm-6 col-lg-5 gambar">
         <div class="panel d-flex align-content-center justify-content-center flex-wrap"><img src="{% static 'images/PintuKeraton.jpg' %}" alt="Sebuah Pintu di Keraton" class="fotoingrid"></div>     
      </div>
    </div>
  </div>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  </body>
</html>

ppwstory4/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>
<body>
    <h1>Hello My Name is {{ name }}</h1>
</body>
</html>

ppwstory4/templates/mainbootstrap.html
<!DOCTYPE html>
{% load static %}
<head>
	<meta charset = "UTF-8">
	<title>Website Saya</title>
	<link href="https://fonts.googleapis.com/css?family=Encode+Sans+Semi+Condensed&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> 
	<link rel = "stylesheet"
   		type = "text/css"
   		href = "{% static 'cssStory3.css' %}" />
</head>
 
<body data-spy="scroll" data-target="#collapsibleNavbar">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  		<span class="navbar-brand" href="#">i am <b>uqi</b></span>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  		</button>
	  	<div class="collapse navbar-collapse" id="collapsibleNavbar">
	    	<ul class="navbar-nav ml-auto">
		    	<li class="nav-item">
		    		<a class="active nav-link" href="#">HOME</a></li>
		    	<li class="nav-item">
		    		<a class="nav-link" href="{% url 'ppwstory4:about' %}">about</a></li>
		  		<li class="nav-item">
		  			<a class="nav-link" href="{% url 'ppwstory4:gallery' %}">gallery</a></li>  		
			</ul>
	 	</div>
	</nav>

	<div class="frontPage" style="background-image: url({%static 'images/fotoDepanContoh1.png' %})">

		<div class="nama">i am <strong>Sya<u>uqi</u> Muhammad Dhiya Ulhaq</strong></div>
	</div>

		<p class="bio">a informatics system student that into photography,<br>
		videography, cats, city buses, and HIMYM tv series.<br>
		still learn about programming and try to be<br>
		the best son to his parent</p>
		<p class="contact">contact me:</p>
		<div class="redirect-contact">
			<a href="https://twitter.com/uqiiiiiii">twitter</a>
			<a href="https://www.instagram.com/uqi621/">instagram</a>
			<a href="https://gitlab.com/uqi621">gitlab</a>
			<a href="mailto:symdu31@gmail.com">email</a>
		</div>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
	</body>
</html>